kind: pipeline
type: docker
name: default

steps:
  - name: publish-tag
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      repo: thejanne/bztt-server
      username: thejanne
      password:
        from_secret: PLUGIN_AUTH
      tags:
        - ${DRONE_TAG}

  - name: publish-master
    image: plugins/docker
    when:
      event:
        - push
      branch:
        - master
    settings:
      repo: thejanne/bztt-server
      username: thejanne
      password:
        from_secret: PLUGIN_AUTH
      tags:
        - latest
